name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
      - run: yarn
      - run: yarn lint

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
      - run: yarn
      - run: yarn test

  test-run:
    name: Test repositories
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: repositories
          key: v2-${{ hashFiles('repositories.json') }}
      - uses: actions/setup-node@v6
      - run: yarn
      - run: yarn execute "RUN https://pkg.pr.new/prettier/prettier@main VS https://pkg.pr.new/prettier/prettier@main ON shoelace-style/webawesome"
